### ISSUE TITLE
`rol @`

### ISSUE THREAD

**Issue by tom-seddon** [dmsc/zx02#3]
Hopefully not too dumb a question, but: what assembler is this for? What does `rol @` assemble to?

None of the `@` labels look like they can be usefully rol'd. Is this rol accumulator rather than rol memory?

**Comment by dmsc** [comment]
Hi!

Yes, the `rol @` idiom is used on some assemblers to mean "rol accumulator".

The files in the repository are meant to be assembled with the MADS assembler, its syntax is documented at https://mads.atari8.info/mads_eng.html

Have Fun!
