### ISSUE TITLE
memory leak in compressor code

### ISSUE THREAD

**Issue by pararaum** [dmsc/zx02#4]
Hi! The compressor code is very nice but it has a memory leak.

In memory.c and optimize.c multiple time `malloc()` is called but the memory is never freed. This causes a memory leak. Could you please provide a "freezx02memory()" function or the like which does the cleanup? This would make it easier to integrate the compressor in other software.

Thanks!

**Comment by dmsc** [comment]
I added a new struct to keep track of allocations, see https://github.com/dmsc/zx02/commit/86b493c6cb7f0109268e7c53379a649ae0c2e833 , but in case of memory errors the compressor calls "exit()", so no memory is freed.

To properly use this in a library, it should better handle error cases, and probably signal the compression status in a better way.
